### ISSUE TITLE
这两个地方扔参，导致一些配置无效，比如`setVisibility`

### ISSUE THREAD

**Issue by allowing** [freyo/flysystem-qcloud-cos-v5#14]
https://github.com/freyo/flysystem-qcloud-cos-v5/blob/5145cdae20acf3bb6f9ad8a58991726ccf430610/src/Adapter.php#L153

https://github.com/freyo/flysystem-qcloud-cos-v5/blob/5145cdae20acf3bb6f9ad8a58991726ccf430610/src/Adapter.php#L165

**Comment by allowing** [comment]
对，最后的config参数没有应用，直接舍弃了

**Comment by freyo** [comment]
这个问题我后面处理一下。

之前移除的原因主要是 COS V5 版本限制了访问策略的规则数量，**ACL + Policy 最大 1000 条**，超过限制后将出现无法设置新的访问策略规则，无法创建新的Bucket等问题。

目前建议不要对每个文件单独设置权限，否则很容易超限；最好是在上级对象设置权限，下级对象继承权限。

**Comment by freyo** [comment]
c5ce0263e27e135081f4add7f4739548e4472bd2 已处理
