### ISSUE TITLE
GetFederationToken插件没有默认启用？

### ISSUE THREAD

**Issue by skys215** [freyo/flysystem-qcloud-cos-v5#17]
你好
   我刚开始用这个库。想要用这个实现生成临时上传凭证，让小程序直接上传文件到cos上。
   我发现代码中已经实现了`getFederationToken`方法，然而并没有默认启用。
   需要在需要调用`getFederationToken`的地方，手动启用插件。
```php
$disk->addPlugin(new \Freyo\Flysystem\QcloudCOSv5\Plugins\GetFederationToken());
```
方可调用`getFederationToken`方法生成上传凭证。
```php
$token = $disk->getFederationToken();
```

是否有计划默认启用`getFederationToken`？
谢谢

**Comment by freyo** [comment]
该插件目前还处于测试中，计划下个版本默认启用。

**Comment by skys215** [comment]
好的。
