### ISSUE TITLE
5.7 的框架没法安装，carbon 扩展的版本冲突

### ISSUE THREAD

**Issue by Jasongzj** [freyo/flysystem-qcloud-cos-v5#22]
安装扩展包时，提示 5.7 框架安装的 `nesbot/carbon`版本是 2.16.0。
但是这个扩展包 require 的是 `~1.0`，有没有兼容 `~2.0` 的版本呢？

**Comment by freyo** [comment]
1.3.2 已支持 Carbon 2

**Comment by Jasongzj** [comment]
> 1.3.2 已支持 Carbon 2

哇，想着急用直接composer update换了旧版的carbon，没想到这么快发了，谢谢！
