### ISSUE TITLE
getUrl时文件无后缀

### ISSUE THREAD

**Issue by YangEndly** [freyo/flysystem-qcloud-cos-v5#24]
`$disk = Storage::disk('cosv5');`
 `//$exists = $disk->put('/'.md5_file(public_path().'\lg.jpg').'.jpg',$fileContents);`
        
`$url = $disk->url('/'.md5_file(public_path().'\lg.jpg'));`
        
`$temporaryUrl = $disk->temporaryUrl('/'.md5_file(public_path().'\lg.jpg'), Carbon::now()->addMinutes(5));`
    
 `var_dump($url);`
       
`echo '<br/>';`

` var_dump($temporaryUrl);`

上面是我的测试代码

`string(85) "https://test-1258858940.cos.ap-shanghai.myqcloud.com/89babd0924649ca463ff4988f7ce4680" 
string(341) "https://test-1258858940.cos.ap-shanghai.myqcloud.com/89babd0924649ca463ff4988f7ce4680?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDKQQFpASApGSTJILWmna8VhiU4QYRiYpw%26q-sign-time%3D1554363195%3B1554363555%26q-key-time%3D1554363195%3B1554363555%26q-header-list%3Dhost%26q-url-param-list%3D%26q-signature%3D6a17711eb0db254a4ec67d8699acfdae7bac3fff"`

两个Url中都没有文件后缀，看看是我的姿势不对吗？

**Comment by freyo** [comment]
你 path 没有带后缀哦
```
$disk->url('/'.md5_file(public_path().'\lg.jpg').'.jpg');
```
