### ISSUE TITLE
文件夹无法删除

### ISSUE THREAD

**Issue by dianmx** [freyo/flysystem-qcloud-cos-v5#25]
文件夹无法删除是什么原因。

可以创建文件和文件夹，也可以删除文件，就是按照同样的方式传入PATH删除文件夹失败。

提示
strpbrk() expects parameter 1 to be string, array given

**Comment by freyo** [comment]
请问是用 `$disk->delete()` 还是 `$disk->deleteDir()` 操作的？

**Comment by dianmx** [comment]
是按照以下这样子写的，deleteDir 和 deleteDirectory 结果都是出错。只有选择的文件可以删除，其他文件夹及下面的子文件都是失败的。

···
foreach ($request->path as $media_url) {
                $files = collect(Storage::listContents($media_url, true));
                if ($files->count()) {
                    foreach ($files as $item) {
                        if ($item['type'] == 'dir') {
                            Storage::deleteDirectory($media_url);
                        }
                        if ($item['type'] == 'file') {
                            Storage::delete($media_url);
                        }
                    }
                } else {
                    Storage::delete($media_url);
                }
            }
···

**Comment by freyo** [comment]
升级到 [1.4.0](https://github.com/freyo/flysystem-qcloud-cos-v5/releases/tag/1.4.0) 再尝试一下？

**Comment by dianmx** [comment]
是版本问题，1.40 问题已解决，谢谢。
