### ISSUE TITLE
qcloud/cos-sdk-v5 升级v1.3.4 以后，在Laravel中调用 get 或 read方法会报错

### ISSUE THREAD

**Issue by Roachard** [freyo/flysystem-qcloud-cos-v5#29]
qcloud/cos-sdk-v5 更新了v1.3.4，似乎是把Guzzle从3升级到了6，这在目前的最新版 flysystem-qcloud-cos-v5 （v1.4.3）中会导致报错：
```
PHP Error:  Call to undefined method GuzzleHttp/Command/Result::get() in /var/www/************/vendor/freyo/flysystem-qcloud-cos-v5/src/Adapter.php on line 315
```

Adapter.php 中使用了 $response->get('Body') 来获取请求到的文件，而在v1.3.4 的 qcloud/cos-sdk-v5 中，这里拿到的 $response 已经是 `GuzzleHttp\Command\Result Object` 了，它没有get方法。

**Comment by freyo** [comment]
已确认此问题

**Comment by freyo** [comment]
目前已锁定 **1.3.3** 版本以保证正常使用。后续会跟进兼容 **Guzzle 6**。

如已升级  `qcloud/cos-sdk-v5:v1.3.4` ，请重新执行以下命令降级。
```
composer update freyo/flysystem-qcloud-cos-v5 -vvv
```
