### ISSUE TITLE
你好，我想问一下获取文件链接为什么会带一个签名。可以去掉吗？

### ISSUE THREAD

**Issue by sirRen** [freyo/flysystem-qcloud-cos-v5#35]

**Comment by freyo** [comment]
你是通过什么方法获取文件链接的？可以的话麻烦贴一下示例代码。

**Comment by sirRen** [comment]
Adapter类的getUrl函数，获取的文件名会调用createPresignedUrl函数添加一个签名

**Comment by freyo** [comment]
> Adapter类的getUrl函数，获取的文件名会调用createPresignedUrl函数添加一个签名

你可以配置一下CDN参数，这样会直接拼接CDN地址。

**Comment by sirRen** [comment]
好的。谢谢

**Comment by sirRen** [comment]
好的。谢谢
