### ISSUE TITLE
请支持一下laravel8 谢谢！安装提示guzzlehttp 低于7.2.0 ，谢谢你！

### ISSUE THREAD

**Issue by 8108905** [freyo/flysystem-qcloud-cos-v5#42]
`  Problem 1
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - freyo/flysystem-qcloud-cos-v5 2.0.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.0.1 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.0.2 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.0.3 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - freyo/flysystem-qcloud-cos-v5 2.1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for freyo/flysystem-qcloud-cos-v5 ^2.0 -> satisfiable by freyo/flysystem-qcloud-cos-v5[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0].

Installation failed, reverting ./composer.json to its original content.
`

**Comment by freyo** [comment]
2.1.1 fixed

**Comment by 8108905** [comment]
Laravel8 会有以下提示
composer require "freyo/flysystem-qcloud-cos-v5:^2.1.1" -vvv

Dependency resolution completed in 0.002 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for freyo/flysystem-qcloud-cos-v5 ^2.1.1 -> satisfiable by freyo/flysystem-qcloud-cos-v5[2.1.1].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
    - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
    - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].


Installation failed, reverting ./composer.json to its original content.

**Comment by freyo** [comment]
> Laravel8 会有以下提示
> composer require "freyo/flysystem-qcloud-cos-v5:^2.1.1" -vvv
> 
> Dependency resolution completed in 0.002 seconds
> Your requirements could not be resolved to an installable set of packages.
> 
> Problem 1
> - Installation request for freyo/flysystem-qcloud-cos-v5 ^2.1.1 -> satisfiable by freyo/flysystem-qcloud-cos-v5[2.1.1].
> - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
> - Can only install one of: guzzlehttp/guzzle[7.2.0, 6.5.x-dev].
> - Can only install one of: guzzlehttp/guzzle[6.5.x-dev, 7.2.0].
> - Conclusion: install guzzlehttp/guzzle 6.5.x-dev
> - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
> 
> Installation failed, reverting ./composer.json to its original content.

本项目依赖官方SDK，官方SDK未支持Guzzle7。

**Comment by freyo** [comment]
可以先尝试使用 https://github.com/overtrue/qcloud-cos-client

**Comment by 8108905** [comment]
好的谢谢你
