### ISSUE TITLE
Can I customize the request header

### ISSUE THREAD

**Issue by 81867370** [freyo/flysystem-qcloud-cos-v5#47]
I want to use it with the [qcloud-documents](https://github.com/tencentyun/qcloud-documents)  interface. I need to customize the request header. `flysystem-qcloud-cos-v5`  How do I add it

**Comment by freyo** [comment]
```php
$disk = Storage::disk('cosv5');

// create a file
$disk->put('avatars/1', $fileContents, ['params' => [
    'ContentType' => 'image/png',
]]);
```
available parameters,  see https://github.com/tencentyun/cos-php-sdk-v5/blob/master/src/Qcloud/Cos/Service.php#L1191

**Comment by freyo** [comment]
try
```php
$disk = Storage::disk('cosv5');

// create a file
$disk->put('avatars/1', $fileContents, ['params' => [
    'PicOperations' => '{"is_pic_info":1,"rules":[{"fileid":"test.jpg","rule":"imageView2/format/png"}]}',
]]);
```

**Comment by 81867370** [comment]
Thank you very much for your help, your code can be implemented.I also have a question, how to judge whether the file has been uploaded successfully?  It seems that there is no information returned, so we can only judge by `try` `catch`
