### ISSUE TITLE
url获取的上传地址后面可以不加后缀吗

### ISSUE THREAD

**Issue by sherry718** [freyo/flysystem-qcloud-cos-v5#50]
图片链接后面的参数信息
“?sign=q-sign-algorithm%3Dsha1%26q-ak%3DAKIDLh2UwFSdkiU6bv1ua3IK8k9KGxPcaKq6%26q-sign-time%3D1641700054%3B1641701914%26q-key-time%3D1641700054%3B1641701914%26q-header-list%3Dhost%26q-url-param-list%3D%26q-signature%3D934baaff9a2ae28bb29518ba84a5688f61d56168&
是不是可以去掉

**Comment by freyo** [comment]
配置一下CDN域名即可

**Comment by sherry718** [comment]
配置了自定义域名不行，一定要是cdn域名吗，这个需要开通cdn服务。代码获取方式还是->url()吧

**Comment by freyo** [comment]
腾讯云默认域名也是可以的，不一定要自定义域名。

添加以下配置即可
```php
$config = [
     ...
     'cdn' => 'https://xxxx.com',
];
```

**Comment by sherry718** [comment]
好的 谢谢

**Comment by yexk** [comment]
> 腾讯云默认域名也是可以的，不一定要自定义域名。
> 
> 添加以下配置即可
> 
> ```
> $config = [
>      ...
>      'cdn' => 'https://xxxx.com',
> ];
> ```

我试了下。配置了cdn就不会带签名了，如果是私有读写就会访问失败。
