### ISSUE TITLE
v5 版CopySource获取方式变了，建议修改，不然好像 复制、重命名会出错

### ISSUE THREAD

**Issue by walkpan** [freyo/flysystem-qcloud-cos-v5#8]
## copyobject(简单复制)
/*
 * 将{bucket},{region},{cos_path},{versionId}替换成复制源的真实信息
 */
try {
    $result = $cosClient->copyObject(array(
        'Bucket' => $bucket,
        'CopySource' => '{bucket}.cos.{region}.myqcloud.com/{cos_path}?versionId={versionId}',
        'Key' => 'string',
    ));
    print_r($result);
} catch (\Exception $e) {
    echo "$e\n";
}

**Comment by freyo** [comment]
已修复。操作大文件需要分块。

**Comment by walkpan** [comment]
我是laravel 5.6 ，更新后1.1.4.1后小程序还是报
```
Qcloud\Cos\Exception\NoSuchBucketException: Failed to query the state of source object in file C:\laragon\www\yesapi\vendor\qcloud\cos-sdk-v5\src\Qcloud\Cos\ExceptionListener.php on line 57
Stack trace:
```
错误
更改
```
public function getSourcePath($path)
    {
        return sprintf('%s.cos.%s.myqcloud.com/%s',
            $this->getBucket(), $this->getRegion(), $path
        );
    }
```后能正确重命名，copy没试

**Comment by freyo** [comment]
`NoSuchBucketException` 异常表示你的bucket不存在

**Comment by walkpan** [comment]
原来如此😄，我的bucket是带appid的
